# Generated by Django 2.2.6 on 2019-10-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='vaccinations',
            new_name='name',
        ),
    ]
